name = "hajj-lottery-simulator"
compatibility_date = "2026-08-09"
pages_build_output_dir = "dist"

# Cloudflare Pages D1 binding used by functions/api/attempt.ts

[[d1_databases]]
binding = "hajj_lottery_db"
database_name = "hajj-lottery-db"
database_id = "d207b715-bd6a-4de7-b892-6a4fee7d9da9"
